### ISSUE TITLE
Unable to run cronjob

### ISSUE THREAD

**Issue by Parakoopa** [FACT-Finder-Web-Components/magento2-module#130]
- FACT-Finder-Web-Components Magento2-Module version (see composer.json): 
1.1

- Magento edition and version: 
Magento Commerce 2.3.1

- PHP version: 
7.1

- Expected behavior: 
The cronjob for feed export is ran

- Actual behavior: 
The following fatal PHP error occurs
```PHP Fatal error:  Uncaught Error: Cannot instantiate interface Omikron\Factfinder\Api\Config\ChannelProviderInterface in /src/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:50
Stack trace:
#0 /src/www/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Omikron\\Factfin...')
#1 /src/www/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(160): Magento\Framework\ObjectManager\ObjectManager->get('Omikron\\Factfin...')
#2 /src/www/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(246): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Omikron\\Factfin...', NULL, 'channelProvider', 'Omikron\\Factfin...')
#3 /src/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Omikron\\Factfin...', Array, Array)
#4 /src/www/vendor/magento/framework/ObjectManager/Factory/Dyna in /src/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 50

Fatal error: Uncaught Error: Cannot instantiate interface Omikron\Factfinder\Api\Config\ChannelProviderInterface in /src/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:50
Stack trace:
#0 /src/www/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Omikron\\Factfin...')
#1 /src/www/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(160): Magento\Framework\ObjectManager\ObjectManager->get('Omikron\\Factfin...')
#2 /src/www/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(246): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Omikron\\Factfin...', NULL, 'channelProvider', 'Omikron\\Factfin...')
#3 /src/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Omikron\\Factfin...', Array, Array)
#4 /src/www/vendor/magento/framework/ObjectManager/Factory/Dyna in /src/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 50
```

- Steps to reproduce: 
1. Run the feed export via Magento crontab or n98-magerun2 (sys:cron:run factfinder_feed_export).

I think the issue is, that the parameter $channelProvider for Omikron\Factfinder\Cron\Feed has no concrete class defined in any of the di.xml files.

**Comment by Parakoopa** [comment]
Also the parameter $type is not set. In the crontab/di.xml virtual types for product/cms export are defined. I guess adding $channelProvider for CMS/product export there and then adding the virtual types to the Crontab (splitting it into two cron jobs) should fix the issue?

**Comment by Parakoopa** [comment]
I opened a pull request for this: #131

**Comment by a-laurowski** [comment]
Hi @Parakoopa 
Thanks for Your PR. I've already approve it. Your fix will be released in next minor version.

**Comment by a-laurowski** [comment]
Hey @Parakoopa . New version of module containing Your fix was just released
https://github.com/FACT-Finder-Web-Components/magento2-module/releases/tag/v1.1.2
