### ISSUE TITLE
Argument 1 passed to ...\ExtendedTextFilter::filterValue() must be of the type string, bool given

### ISSUE THREAD

**Issue by Parakoopa** [FACT-Finder-Web-Components/magento2-module#268]
- FACT-Finder-Web-Components Magento2-Module version (see composer.json): 1.6.2
- Magento edition and version: Commerce 2.3.5
- PHP version: 7.3.19
- Expected behavior: The product export processes without an error 
- Actual behavior: The following error is raised:
```
Fatal error: Uncaught TypeError: Argument 1 passed to Omikron\Factfinder\Model\Filter\ExtendedTextFilter\Interceptor::filterValue() must be of the type string, bool given, called in /src/vendor/omikron/magento2-factfinder/src/Model/Export/Catalog/ProductType/ConfigurableDataProvider.php on line 89 and defined in /src/generated/code/Omikron/Factfinder/Model/Filter/ExtendedTextFilter/Interceptor.php:19
Stack trace:
#0 /src/vendor/omikron/magento2-factfinder/src/Model/Export/Catalog/ProductType/ConfigurableDataProvider.php(89): Omikron\Factfinder\Model\Filter\ExtendedTextFilter\Interceptor->filterValue(false)
#1 [internal function]: Omikron\Factfinder\Model\Export\Catalog\ProductType\ConfigurableDataProvider->Omikron\Factfinder\Model\Export\Catalog\ProductType\{closure}(Array, Array)
#2 /src/vendor/omikron/magento2-factfinder/src/Model/Export/Catalog/ProductType/ConfigurableDataProvider.php(92): array_reduce(Array, Object(Closure), Array)
#3 /src/vendor/omikron/magento2-factfinder/src/Model/Export/Catalog/ProductType/Configu in /src/generated/code/Omikron/Factfinder/Model/Filter/ExtendedTextFilter/Interceptor.php on line 19
```
- Steps to reproduce: Not sure

There is a note and a hotfix at that position, for when the label value is null. 
It seems that the value can also be a boolean now with Magento 2.3.5+.

**Comment by Parakoopa** [comment]
Nevermind, I just noticed that was added by a patch by us.
So it seems that for some reason either null and bool can be values that are returned for the labels, in both cases the exception above is raised.

**Comment by Parakoopa** [comment]
For reference, this is the patch we currently have in place. I guess I could extend it to check `is_string` instead, but the question remains why this happens. I'm not 100% sure it's caused by the FACT-Finder module either, it could also be faulty product data.

```patch
diff --git www/vendor/omikron/magento2-factfinder/src/Model/Export/Catalog/ProductType/ConfigurableDataProvider.php www/vendor/omikron/magento2-factfinder/src/Model/Export/Catalog/ProductType/ConfigurableDataProvider.php
index 8386b2f..397b7eb 100644
--- www/vendor/omikron/magento2-factfinder/src/Model/Export/Catalog/ProductType/ConfigurableDataProvider.php
+++ www/vendor/omikron/magento2-factfinder/src/Model/Export/Catalog/ProductType/ConfigurableDataProvider.php
@@ -76,8 +76,15 @@ class ConfigurableDataProvider extends SimpleDataProvider

     private function getOptions(Product $product): array
     {
-        return array_reduce($this->productType->getConfigurableOptions($product), function (array $res, array $option) {
-            foreach ($option as ['sku' => $sku, 'super_attribute_label' => $label, 'option_title' => $value]) {
+        return array_reduce($this->productType->getConfigurableOptions($product), function (array $res, array $option) use ($product) {
+            foreach ($option as ['sku' => $sku, 'super_attribute_label' => $label, 'option_title' => $value, 'attribute_code' => $attributeCode]) {
+                // Fixes Fatal error: Uncaught TypeError: Argument 1 passed to Omikron\Factfinder\Model\Filter\ExtendedTextFilter::filterValue() must be of the type string, null given
+                // This is just a hotfix, sometimes there is no frontend label returned which leads to an error, further analysis required
+                if (is_null($label)) {
+                    try {
+                        $label = $product->getResource()->getAttribute($attributeCode)->getFrontend()->getLabel($product);
+                    } catch (\Exception $e) {}
+                }
                 $res[$sku][] = "{$this->filter->filterValue($label)}={$this->filter->filterValue($value)}";
             }
             return $res;

```

**Comment by Parakoopa** [comment]
The issue was indeed just faulty product data, after adding some logging we were able to find the broken products.
