### ISSUE TITLE
TypeError on HTTP product export

### ISSUE THREAD

**Issue by simonrl** [FACT-Finder-Web-Components/magento2-module#434]
- FACT-Finder-Web-Components Magento2-Module version (see composer.json): v3.7.2
- Magento edition and version: Commerce 2.4.5
- PHP version: 8.1
- Expected behavior: HTTP feed export for products is working
- Actual behavior: HTTP feed export for products gives a 500 error
- Steps to reproduce: call via browser / curl: <shop-url>/factfinder/export/product/store/1

I get the following error message & trace in system.log:

```
report.CRITICAL: TypeError: Magento\Bundle\Model\Link::setExtensionAttributes(): Argument #1 ($extensionAttributes) must be of type Magento\Bundle\Api\Data\LinkExtensionInterface, Magento\Catalog\Api\Data\ProductExtension given, called in /magento2/www/vendor/magento/framework/Api/DataObjectHelper.php on line 137 and defined in /magento2/www/vendor/magento/module-bundle/Model/Link.php:214
Stack trace:
#0 /magento2/www/vendor/magento/framework/Api/DataObjectHelper.php(137): Magento\Bundle\Model\Link->setExtensionAttributes(Object(Magento\Catalog\Api\Data\ProductExtension))
#1 /magento2/www/vendor/magento/framework/Api/DataObjectHelper.php(85): Magento\Framework\Api\DataObjectHelper->_setDataValues(Object(Magento\Bundle\Model\Link), Array, 'Magento\\Bundle\\...')
#2 /magento2/www/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\Api\DataObjectHelper->populateWithArray(Object(Magento\Bundle\Model\Link), Array, 'Magento\\Bundle\\...')
#3 /magento2/www/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Api\DataObjectHelper\Interceptor->___callParent('populateWithArr...', Array)
#4 /magento2/www/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\Api\DataObjectHelper\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Bundle\Model\Link), Array, 'Magento\\Bundle\\...')
#5 /magento2/www/generated/code/Magento/Framework/Api/DataObjectHelper/Interceptor.php(23): Magento\Framework\Api\DataObjectHelper\Interceptor->___callPlugins('populateWithArr...', Array, Array)
#6 /magento2/www/vendor/magento/module-bundle/Model/Product/LinksList.php(77): Magento\Framework\Api\DataObjectHelper\Interceptor->populateWithArray(Object(Magento\Bundle\Model\Link), Array, 'Magento\\Bundle\\...')
#7 /magento2/www/vendor/magento/module-bundle/Model/Product/OptionList.php(68): Magento\Bundle\Model\Product\LinksList->getItems(Object(Magento\Catalog\Model\Product\Interceptor), '2')
#8 /magento2/www/vendor/magento/module-bundle/Model/OptionRepository.php(142): Magento\Bundle\Model\Product\OptionList->getItems(Object(Magento\Catalog\Model\Product\Interceptor))
#9 /magento2/www/vendor/magento/module-bundle/Model/Product/ReadHandler.php(44): Magento\Bundle\Model\OptionRepository->getListByProduct(Object(Magento\Catalog\Model\Product\Interceptor))
#10 /magento2/www/vendor/magento/framework/EntityManager/Operation/Read/ReadExtensions.php(48): Magento\Bundle\Model\Product\ReadHandler->execute(Object(Magento\Catalog\Model\Product\Interceptor), Array)
#11 /magento2/www/vendor/magento/module-catalog/Model/ProductRepository.php(730): Magento\Framework\EntityManager\Operation\Read\ReadExtensions->execute(Object(Magento\Catalog\Model\Product\Interceptor))
#12 /magento2/www/vendor/magento/module-catalog/Model/ProductRepository.php(700): Magento\Catalog\Model\ProductRepository->addExtensionAttributes(Object(Magento\Catalog\Model\ResourceModel\Product\Collection\Interceptor))
#13 /magento2/www/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Catalog\Model\ProductRepository->getList(Object(Magento\Framework\Api\SearchCriteria))
#14 /magento2/www/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Model\ProductRepository\Interceptor->___callParent('getList', Array)
#15 /magento2/www/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Model\ProductRepository\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\Api\SearchCriteria))
#16 /magento2/www/generated/code/Magento/Catalog/Model/ProductRepository/Interceptor.php(59): Magento\Catalog\Model\ProductRepository\Interceptor->___callPlugins('getList', Array, Array)
#17 /magento2/www/vendor/omikron/magento2-factfinder/src/Model/Export/Catalog/Products.php(48): Magento\Catalog\Model\ProductRepository\Interceptor->getList(Object(Magento\Framework\Api\SearchCriteria))
#18 /magento2/www/vendor/omikron/magento2-factfinder/src/Model/Export/Catalog/DataProvider.php(46): Omikron\Factfinder\Model\Export\Catalog\Products->getIterator()
#19 /magento2/www/vendor/omikron/magento2-factfinder/src/Model/Exporter.php(25): Omikron\Factfinder\Model\Export\Catalog\DataProvider->getEntities()
#20 /magento2/www/vendor/omikron/magento2-factfinder/src/Model/Export/Feed.php(46): Omikron\Factfinder\Model\Exporter->exportEntities(Object(Omikron\Factfinder\Model\Stream\Csv), Object(Omikron\Factfinder\Model\Export\Catalog\DataProvider), Array)
#21 /magento2/www/vendor/omikron/magento2-factfinder/src/Controller/Export/Product.php(64): Omikron\Factfinder\Model\Export\Feed->generate(Object(Omikron\Factfinder\Model\Stream\Csv))
#22 /magento2/www/vendor/omikron/magento2-factfinder/src/Model/StoreEmulation.php(33): Omikron\Factfinder\Controller\Export\Product->Omikron\Factfinder\Controller\Export\{closure}()
#23 /magento2/www/vendor/omikron/magento2-factfinder/src/Controller/Export/Product.php(66): Omikron\Factfinder\Model\StoreEmulation->runInStore(1, Object(Closure))
#24 /magento2/www/vendor/magento/framework/Interception/Interceptor.php(58): Omikron\Factfinder\Controller\Export\Product->execute()
#25 /magento2/www/vendor/magento/framework/Interception/Interceptor.php(138): Omikron\Factfinder\Controller\Export\Product\Interceptor->___callParent('execute', Array)
#26 /magento2/www/vendor/magento/framework/Interception/Interceptor.php(153): Omikron\Factfinder\Controller\Export\Product\Interceptor->Magento\Framework\Interception\{closure}()
#27 /magento2/www/generated/code/Omikron/Factfinder/Controller/Export/Product/Interceptor.php(23): Omikron\Factfinder\Controller\Export\Product\Interceptor->___callPlugins('execute', Array, Array)
#28 /magento2/www/vendor/magento/framework/App/Action/Action.php(111): Omikron\Factfinder\Controller\Export\Product\Interceptor->execute()
#29 /magento2/www/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#30 /magento2/www/vendor/magento/framework/Interception/Interceptor.php(138): Omikron\Factfinder\Controller\Export\Product\Interceptor->___callParent('dispatch', Array)
#31 /magento2/www/vendor/magento/framework/Interception/Interceptor.php(153): Omikron\Factfinder\Controller\Export\Product\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#32 /magento2/www/generated/code/Omikron/Factfinder/Controller/Export/Product/Interceptor.php(32): Omikron\Factfinder\Controller\Export\Product\Interceptor->___callPlugins('dispatch', Array, Array)
#33 /magento2/www/vendor/magento/framework/App/FrontController.php(245): Omikron\Factfinder\Controller\Export\Product\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#34 /magento2/www/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse(Object(Omikron\Factfinder\Controller\Export\Product\Interceptor), Object(Magento\Framework\App\Request\Http))
#35 /magento2/www/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Omikron\Factfinder\Controller\Export\Product\Interceptor))
#36 /magento2/www/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#44 /magento2/www/vendor/magento/framework/Interception/Interceptor.php(153): Magento\PageCache\Model\App\FrontController\BuiltinPlugin\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#45 /magento2/www/generated/code/Magento/PageCache/Model/App/FrontController/BuiltinPlugin/Interceptor.php(23): Magento\PageCache\Model\App\FrontController\BuiltinPlugin\Interceptor->___callPlugins('aroundDispatch', Array, NULL)
#46 /magento2/www/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin\Interceptor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#47 /magento2/www/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#48 /magento2/www/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#49 /magento2/www/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#50 /magento2/www/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#51 /magento2/www/pub/index.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#52 {main} [] []
```

**Comment by grzegorz-jamroz** [comment]
Hi @simonrl,

thank you for reporting. I will try to check it today.

**Comment by grzegorz-jamroz** [comment]
Hi @simonrl,

I have checked how export works in
- SDK version v3.7.3 
- Magento ver. 2.4.4
- PHP 8.1.14
- via browser: /factfinder/export/product/store/1

It works correct. I will try to debug code dipper but can't promise anything.

**Comment by simonrl** [comment]
Hi @grzegorz-jamroz 

thanks for testing.

I tried again and found that the error occurs when at least 1 bundle product is enabled.

When I disable all bundle products from our website, the error is gone.

-- Simon

**Comment by grzegorz-jamroz** [comment]
Hi @simonrl,

I am using export with bundle products without any problem but I prepared few other fixes which maybe somehow helps you.

I will soon prepare new release.

Greg
